### ISSUE TITLE
Node.JS 14 is getting deprecated in GCP

### ISSUE THREAD

**Issue by volodymyr-shpylka-aitastic** [pangeacyber/pangea-extensions-firebase#32]
Hello,

we have got a message from GCP that Node.JS version 14 is getting deprecated soon for Cloud Functions. (as well as every Node.JS version older than and including 16).

This extension is based on cloud functions and is currently showing a deprecation warning in GCP. This version is deprecated since Jan 2024. According to Google "Deprecated runtimes will be decommissioned after a period of 6 - 12 months." So there is a chance that the extension will stop working in 3 months.

Is it possible to update the extension to Node.JS 20?

**Comment by kenany** [comment]
Each extension has been updated to Node.js v18 as of the following versions:
- firestore-audit-document v0.1.0
- firestore-audit-log v0.1.0
- firestore-redact-text v0.1.0
- storage-file-intel v0.2.0

**Comment by volodymyr-shpylka-aitastic** [comment]
This update seems to have broken the "isolate" functionaliy of the storage-file-intel extension. Malicious files are getting deleted, but we now don't get a zip file inside the /malicious (default) folder. 

Problematic version: storage-file-intel v0.2.0
Known version without such error: storage-file-intel v0.1.39
Both versions were using the same config.

We are getting following errors:
`Error when attempting to isolating file TypeError: Cannot read properties of undefined (reading 'provider')
    at /workspace/lib/index.js:145:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

and

`Error when attempting to isolating file TypeError: Cannot read properties of undefined (reading 'success')
    at /workspace/lib/index.js:185:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by kenany** [comment]
Thanks for the report. Pushed v0.2.1 with a fix for that, just awaiting approval from the Firebase team.
